name: environment_lpm

dependencies:
  - joblib=0.14.1
  - matplotlib=3.1.1
  - numpy=1.18.1
  - pandas=0.25.1
  - python=3.6.9
  - scikit-learn=0.22
  - seaborn=0.9.0
  - pip:
    - scipy==1.3.3
    - rpy2==3.1.0
